notifications:
  email: false
language: csharp
solution: MathExpressionSolver/MathExpressionSolver.sln
install:
  - nuget restore MathExpressionSolver/MathExpressionSolver.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner 
script:
  - xbuild /p:Configuration=Release MathExpressionSolver/MathExpressionSolver.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./MathExpressionSolver/MathExpressionSolverTests/bin/Release/MathExpressionSolverTests.dll
