notifications:
  email: false
language: csharp
dist: trusty  
env:  
  - CLI_VERSION=latest

addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:  
  - 4.2.3    

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  

  - nuget restore MathExpressionSolver/MathExpressionSolver.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner 
script:
  - build_MES_lib.sh
  - xbuild /p:Configuration=Release MathExpressionSolver/MathExpressionSolver.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./MathExpressionSolver/MathExpressionSolver.Tests/bin/Release/MathExpressionSolverTests.dll
